Add some VimScript lint tools
https://github.com/syngan/vim-vimlint
https://github.com/Kuniwak/vint

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -25,9 +25,45 @@ if [ ! -f "$vimdir/bin/vim" ]; then
 	exit 1
 fi
 
+### Run vint
+############
+failed=0
+printf "Running vint ... "
+if [ -x "$(command -v vint)" ]; then
+  lint=$(vint "$vimgodir" ||:)
+  if [ -n "$lint" ]; then
+    echo "FAILED"
+    echo "$lint"
+    failed=6
+  else
+    echo "PASSED"
+  fi
+else
+  echo "SKIPPED"
+  echo "'vint' binary not found; use 'pip install vim-vint' to install it."
+fi
+
+### Run vim-vimlint
+###################
+printf "\n\nRunning vim-vimlint ... "
+lint=$(sh "$vimdir/share/vim/vimgo/pack/vim-go/start/vim-vimlint/bin/vimlint.sh" \
+  -p "$vimdir/share/vim/vimgo/pack/vim-go/start/vim-vimlparser" \
+  -l "$vimdir/share/vim/vimgo/pack/vim-go/start/vim-vimlint" \
+  -u \
+  -c func_abort=1 \
+  -e EVL110=1 -e EVL103=1 -e EVL104=1 \
+  "$vimgodir" ||:)
+if [ -n "$lint" ]; then
+  echo "FAILED"
+  echo "$lint"
+  failed=6
+else
+  echo "PASSED"
+fi
+
 ### Run vimhelplint.
 ####################
-printf "Running vimhelplint ... "
+printf "\n\nRunning vimhelplint ... "
 
 # set modeline explicitly so that the modeline will be respected when run as root.
 lint=$($vimdir/bin/vim -esNR \
@@ -37,12 +73,13 @@ lint=$($vimdir/bin/vim -esNR \
   +"e $vimgodir/doc/vim-go.txt" \
   +'verbose VimhelpLintEcho' \
   +q \
-  2>&1)
+  2>&1 ||:)
 if [ "$lint" ]; then
   echo "FAILED"
   echo "$lint"
-  exit 6
+  failed=6
 else
   echo "PASSED"
-  exit 0
 fi
+
+exit "$failed"
