Add some VimScript lint tools (#1558)
* Add some VimScript lint tools

https://github.com/syngan/vim-vimlint
https://github.com/Kuniwak/vint

* Remove trailing newlines

* Add augroup to all autocmds

* Fix undefined variables

`l:tmpname` is never defined.

* Explicitly define global variables with g:

* Disable some vint errors

* Change has() syntax to what vimlint wants

* Disable warning for unused variables

Too much effort to fix and vimlint can't deal with closures...

* Install vint in Dockerfile

* Add 2>&1

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -25,6 +25,45 @@ if [ ! -f "$vimdir/bin/vim" ]; then
 	exit 1
 fi
 
+### Run vint
+############
+failed=0
+printf "Running vint ... "
+if [ -x "$(command -v vint)" ]; then
+  lint=$(vint "$vimgodir" 2>&1 ||:)
+  if [ -n "$lint" ]; then
+    echo "FAILED"
+    echo "$lint"
+    echo
+    failed=6
+  else
+    echo "PASSED"
+  fi
+else
+  echo "SKIPPED"
+  echo "'vint' binary not found; use 'pip install vim-vint' to install it."
+fi
+
+### Run vim-vimlint
+###################
+printf "Running vim-vimlint ... "
+lint=$(sh "$vimdir/share/vim/vimgo/pack/vim-go/start/vim-vimlint/bin/vimlint.sh" \
+  -p "$vimdir/share/vim/vimgo/pack/vim-go/start/vim-vimlparser" \
+  -l "$vimdir/share/vim/vimgo/pack/vim-go/start/vim-vimlint" \
+  -u \
+  -c func_abort=1 \
+  -e EVL110=1 -e EVL103=1 -e EVL104=1 -e EVL102=1 \
+  "$vimgodir" \
+  2>&1 ||:)
+if [ -n "$lint" ]; then
+  echo "FAILED"
+  echo "$lint"
+  echo
+  failed=6
+else
+  echo "PASSED"
+fi
+
 ### Run vimhelplint.
 ####################
 printf "Running vimhelplint ... "
@@ -37,12 +76,13 @@ lint=$($vimdir/bin/vim -esNR \
   +"e $vimgodir/doc/vim-go.txt" \
   +'verbose VimhelpLintEcho' \
   +q \
-  2>&1)
+  2>&1 ||:)
 if [ "$lint" ]; then
   echo "FAILED"
   echo "$lint"
-  exit 6
+  failed=6
 else
   echo "PASSED"
-  exit 0
 fi
+
+exit "$failed"
